PactNet/PactVerifierConfig.cs
PactNet/Reporters/Reporter.cs
Samples/EventApi/Provider.Api.Web.Tests/EventAPITests.cs

When using xunit 2 the verification log sent to the standard output isn't captured. I can work around this by setting Console.Out to something which writes to an xunit ITestOutputHelper and then putting it back to the original once the test is complete - but that doesn't play well with tests running in parallel.
So, I've added a config setting that allows adding additional reporters to be set. As the existing tests use the internal constructors that don't use the config object I've added a usage to the samples. Let me know if anything else is needed/more desirable.

Add custom reporters to pact verifier configuration

---

PactNet/Mocks/MockHttpService/Nancy/MockProviderNancyBootstrapper.cs

disable Nancy's default status code handler so 404 and 500 responses aren't clobbered (https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ErrorHandling/DefaultStatusCodeHandler.cs)

disable Nancy's default status code handler

---

PactNet.Tests/Mocks/MockHttpService/Models/HttpBodyContentTests.cs
PactNet/Mocks/MockHttpService/Models/HttpBodyContent.cs

Data serialized to json can take a couple different forms depending on whether you have an object, array, string, or number.  These changes fix how "string-like" data is serialized/deserialized in the request/response "body" of a pact interaction when the "Content-Type" header of the body is "application/json".  For example, below is what an interaction request/response "body" would look like before/after this fix for "string-like" data.
`"headers": { "Content-Type": "application/json; charset=utf-8" },`
`"body": "Hello World"`
`"headers": { "Content-Type": "application/json; charset=utf-8" },`
`"body": "\"Hello World\""`
I have a .NET backend webservice endpoint that returns a single guid or url (it could also be any other .NET primitive that is convertible to a json string as described …

Fix response body json string handling

---

PactNet/Core/PactCoreHost.cs

Error occurs when SSL_CERT_FILE environment variable already exists. The error is:
System.ArgumentException : Item has already been added. Key in dictionary: 'ssl_cert_file' Key being added: 'SSL_CERT_FILE'

fix for issue #95

---

PactNet.Tests/Core/PactVerifierHostConfigTests.cs
PactNet.Tests/PactVerifierTests.cs
PactNet/Core/PactVerifierHostConfig.cs
PactNet/PactVerifier.cs
PactNet/PactVerifierConfig.cs

Per Issue #99
I added two properties on the PactVerifierConfig object and added them to the arguments generated in PactVerifierHostConfig.
I used the optional parameters from `pact-provider-verifier.bat --help verify`

Update PactVerifier to allow for publishing results

---

PactNet.Tests/Core/MockProviderHostConfigTests.cs
PactNet.Tests/IntegrationTests/FailureIntegrationTestsMyApiPact.cs
PactNet.Tests/IntegrationTests/IntegrationTestsMyApiPact.cs
PactNet.Tests/Mocks/MockHttpService/MockProviderServiceTests.cs
PactNet.Tests/PactBuilderTests.cs
PactNet/Core/MockProviderHostConfig.cs
PactNet/IPactBuilder.cs
PactNet/Mocks/MockHttpService/Host/RubyHttpHost.cs
PactNet/Mocks/MockHttpService/MockProviderService.cs
PactNet/PactBuilder.cs

Fix for this issue https://github.com/pact-foundation/pact-mock_service/issues/79

Add an option where the consumer of the library can set the host

---

Build/Download-Standalone-Core.ps1

[This issue](https://github.com/pact-foundation/pact-js/issues/131) is the showstopper of using pact in our company since we have a lot of environments in one URL root.
This issue has been fixed in the commit https://github.com/pact-foundation/pact-provider-verifier/commit/b765b00b9c57300e633afe6044a3459ebf81aeba
Please update nuget packages to resolve this issue in client libs.

Updating to pact standalone core 1.22.1

---

PactNet.Tests/IntegrationTests/FailureIntegrationTestsMyApiPact.cs
PactNet.Tests/IntegrationTests/IntegrationTestsMyApiPact.cs
PactNet.Tests/Mocks/MockHttpService/Host/RubyHttpHostTests.cs
PactNet.Tests/Mocks/MockHttpService/MockProviderServiceTests.cs
PactNet.Tests/PactBuilderTests.cs
PactNet/Mocks/MockHttpService/AdminHttpClient.cs
PactNet/Mocks/MockHttpService/MockProviderService.cs
PactNet/PactBuilder.cs

Isolate the json serializer settings per PactBuilder object instead of using global settings.  This allows us to use multiple PactBuilder objects with different serialization settings for mocking multiple services at the same time.
For example:
I have a service (A) that depends on multiple other services (B + C) that I need to setup separate PactBuilder objects for so that I get separate pact mock services.  Service (B) requires special serialization settings in order to work properly, but changing the global serialization settings would also cause service (C) to use those same settings which won't work for service (C).  This change isolates the serialization settings per PactBuilder object so that each pact mock service can have its own serialization settings.

Isolate the json serializer settings per PactBuilder object

---

README.md

I was following along with the demo and I was initially unable to figure out where `ProviderState` was coming from, this simple update should save future users the trouble I had in looking through the repo to find out where `ProviderState` comes from.

Add declaration of ProviderState to ease use of example

---

README.md

Hi @neilcampbell - I recently gave this PactNet workshop at my work and it seemed to go down pretty well and any minor bits in the write up have been caught now. This PR adds a link to the Readme file to the workshop.
Related Issue: https://github.com/pact-foundation/pact-net/issues/133

Add link to PactNet Workshop to the Readme

---

PactNet.Tests/Core/MockProviderHostConfigTests.cs
PactNet.Tests/IntegrationTests/FailureIntegrationTestsMyApiPact.cs
PactNet.Tests/IntegrationTests/IntegrationTestsMyApiPact.cs
PactNet.Tests/PactBuilderTests.cs
PactNet/Core/MockProviderHostConfig.cs
PactNet/IPactBuilder.cs
PactNet/Mocks/MockHttpService/Host/RubyHttpHost.cs
PactNet/Mocks/MockHttpService/MockProviderService.cs
PactNet/PactBuilder.cs

I've added support for custom SSL, [issue 159](https://github.com/pact-foundation/pact-net/issues/159).
To test you need to do the following steps,
The simplest way to generate a private key and self-signed certificate for localhost is with this openssl command:
``` 
openssl req -x509 -out localhost.crt -keyout localhost.key \
-newkey rsa:2048 -nodes -sha256 \
-subj '/CN=localhost' -extensions EXT -config <( \
printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
```
The above script will generate two files:
- localhost.crt
- localhost.key
Ref. [certificates-for-localhost](https://letsencrypt.org/docs/certificates-for-localhost/).
For windows, import the localhost.crt to the 'Trust Root …

Support custom SSL

---

PactNet/PactUriOptions.cs

This PR makes all properties in PactUriOptions class public. They are readonly properties, so there is no harm done in any case.
It adds a little more comfort working with pact. In my case I have to make a REST call to Pact broker right before verifying pacts in provider to get all pacts for the current provider. For this request I need the same kind of information as for verification: username, password. I think it's more convenient to use same code (class PactUriOptions) in both places and also not to write my own code for creating Basic-authorization value since it's already there

Make properties in PactUriOptions public

---

PactNet.Tests/Builders/MessagePactBuilderTests.cs
PactNet/Builders/MessagePactBuilder.cs

Fix method that identifies previously created pact json file.

Fix GetPactFilePath method in MessagePactBuilder and update unit tests

---

PactNet/Core/PactVerifierHostConfig.cs
PactNet/PactVerifierConfig.cs

Enable `PactVerifierConfig` to accept multiple custom headers.
Discussion here #209

Enable multiple custom headers to be set through PactVerifierConfig

---

PactNet.Tests/Core/MockProviderHostConfigTests.cs
PactNet/Core/MockProviderHostConfig.cs
PactNet/PactConfig.cs

in favor to support following functionality and have clear contract: https://github.com/pact-foundation/pact-mock_service/wiki/Using-the-mock-service-with-CORS

added handling of cors by mock provider

---

PactNet.Tests/Fakes/FakeHttpMessageHandler.cs
PactNet.Tests/IntegrationTests/PactBuilderFailureIntegrationTests.cs
PactNet.Tests/Mocks/MockHttpService/MockProviderServiceTests.cs
PactNet.Tests/PactBuilderTests.cs
PactNet.Tests/PactPublisherTests.cs
PactNet.Tests/PactVerifierTests.cs
PactNet/Core/PactCoreHost.cs
PactNet/Core/PactVerifierHostConfig.cs
PactNet/Extensions/StringExtensions.cs
PactNet/Mocks/MockHttpService/Mappers/HttpMethodMapper.cs
PactNet/Mocks/MockHttpService/MockProviderService.cs
PactNet/PactBuilder.cs
PactNet/PactPublisher.cs
PactNet/PactUriOptions.cs
README.md
README_v1.md
Samples/EventApi/Consumer.Tests/EventsApiConsumerTests.cs
Samples/EventApi/Consumer/EventsApiClient.cs

I was taking a look at the project, and I found a few places where async calls were not awaited. This is a practice that [can lead](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait) to some problems in C#. We should not `.Result` async calls, as that could lead to deadlocks and is considered a bad practice in C#.
I fixed all the instances in tests and README, to better guide people looking at the repository for samples. I also fixed all references that used `String` as a class instead of `string` as a type, as that is also considered a [bad practice](https://blog.paranoidcoding.com/2019/04/08/string-vs-String-is-not-about-style.html).
I couldn't fix all the `.Result` occurrences though, there is a significant …

Fix: await async calls in tests and README, and always use string as a type

---

Build/Download-Standalone-Core.ps1

Hello,
I need to get this new standalone version to include [this change](https://github.com/pact-foundation/pact-ruby/pull/225)

Upgrade to pact ruby standalone 1 88 14

---

README.md

The sample code doesn't compile after copy-paste, the semicolon is not supposed to be there.

docs: Fixed typo in C# sample

---

PactNet.Tests/Core/MockProviderHostConfigTests.cs
PactNet.Tests/Core/PactVerifierHostConfigTests.cs
PactNet.Tests/IntegrationTests/XunitIntegrationTests.cs
PactNet.Tests/Mocks/MockHttpService/Host/RubyHttpHostTests.cs
PactNet.Tests/Mocks/MockHttpService/MockProviderServiceTests.cs
PactNet.Tests/PactNet.Tests.csproj
PactNet.Tests/PactPublisherTests.cs
PactNet/Core/Async.cs
PactNet/Mocks/MockHttpService/MockProviderService.cs
PactNet/PactBuilder.cs
PactNet/PactNet.csproj
appveyor.yml

* Fix deadlock caused by use of `.Result`. Addresses #277 (comment).
* Fix incorrectly named method.
* Use `Path.Combine()` so that the correct directory separator for the operating system is used.
* Use US English for both tenses of _"initialize"_. Also use `nameof()` for the reference to the method name.
* Use the latest version of Visual Studio in AppVeyor ahead of the release of Visual Studio 2022 later this year which will make 2017 even more out-of-date.
* Adds `netstandard2.0` TFM to the PactNet library.
* Updates the tests to use .NET 3.1 instead of 1.1 which is no longer supported.
* Update NuGet package dependencies in the tests, such as xunit, to their latest versions.
* Fix analyzers warnings from xunit.
* Suppress obsolete warning.
I've validated this fix with the private …

fix: Resolve deadlock introduced in 2.6.2

---

build/download-native-libs.sh
samples/EventApi/Consumer.Tests/pacts/Event API Consumer-Event API.json
src/PactNet.Native/IMockServer.cs
src/PactNet.Native/Interop/InteractionHandle.cs
src/PactNet.Native/Interop/InteractionPart.cs
src/PactNet.Native/Interop/LevelFilter.cs
src/PactNet.Native/Interop/NativeInterop.cs
src/PactNet.Native/Interop/PactHandle.cs
src/PactNet.Native/Interop/PactSpecification.cs
src/PactNet.Native/NativeMockServer.cs
src/PactNet.Native/NativePactBuilder.cs
src/PactNet.Native/NativePactVerifier.cs
src/PactNet.Native/NativeRequestBuilder.cs
src/PactNet.Native/NativeResponseBuilder.cs
src/PactNet.Native/PactExtensions.cs
src/PactNet.Native/PactNet.Native.csproj
tests/PactNet.Native.Tests/NativeMockServerTests.cs
tests/PactNet.Native.Tests/NativePactBuilderTests.cs
tests/PactNet.Native.Tests/NativeRequestBuilderTests.cs
tests/PactNet.Native.Tests/NativeResponseBuilderTests.cs
tests/PactNet.Native.Tests/data/v2-consumer-integration.json
tests/PactNet.Native.Tests/data/v3-consumer-integration.json
tests/PactNet.Native.Tests/data/v3-server-integration.json

I've moved the consumer and verifier interop definitions into a single file to make it obvious that the library itself is now a single thing, but maintained the separate interfaces/classes to encapsulate the logic required in each (such as handing the int error codes that you get back from some calls).

feat!: Replace separate FFI libs with new combined FFI lib

---

samples/EventImporter/Consumer.Tests/EventImporterTests.cs
samples/EventImporter/Consumer/EventsWorker.cs
src/PactNet.Native/IMessageMockServer.cs
src/PactNet.Native/NativeMessageBuilder.cs
src/PactNet.Native/NativeMessagePactBuilder.cs
src/PactNet/Exceptions/PactFailureException.cs
src/PactNet/Exceptions/PactMessageConsumerVerificationException.cs
src/PactNet/IMessageBuilder.cs
src/PactNet/PactConfig.cs
tests/PactNet.Native.Tests/NativeMessageBuilderTests.cs
tests/PactNet.Native.Tests/NativePactMessageBuilderTests.cs
tests/PactNet.Native.Tests/PactExtensionsTests.cs
tests/PactNet.Native.Tests/data/v3-message-consumer-integration.json

Fix message pact consumer bodies not respecting default serialisation settings, and add option for providing custom serialiser settings on a per-message basis (to be consistent with the request/response pacts).

fix!: JSON message content respects default serialisation settings

---

.gitignore
src/PactNet.Native/PactVerifier.cs
src/PactNet/IPactVerifier.cs
src/PactNet/LogLevel.cs
tests/PactNet.Native.Tests/PactVerifierTests.cs

Allow the log level to be set to something other than `trace`

feat: Enable configuring provider log level

---

samples/EventImporter/Consumer.Tests/pacts/Event API Consumer V3 Message-Event API V3 Message.json
samples/EventImporter/Provider.Tests/TestStartup.cs
src/PactNet.AspNetCore/Messaging/MessageMiddleware.cs
src/PactNet.AspNetCore/Messaging/MessagingVerifierOptions.cs

The existing pact that's checked in used UpperCamelCase on one side and lowerCamelCase on the other side. This is because on end allows setting JSOn options whereas the other doesn't. This change fixes that.

feat: Allow setting JSON options in message interactions

---

build/download-native-libs.sh
samples/EventApi/Consumer.Tests/EventsApiConsumerTests.cs
samples/EventApi/Consumer.Tests/pacts/Event API Consumer-Event API.json
samples/EventImporter/Consumer.Tests/pacts/Event API Consumer V3 Message-Event API V3 Message.json
samples/ReadMe/pacts/Something API Consumer-Something API.json
src/PactNet.AspNetCore/Messaging/MessageMiddleware.cs
src/PactNet/Interop/InteractionHandle.cs
src/PactNet/Interop/MessageHandle.cs
src/PactNet/Interop/MessagePactHandle.cs
src/PactNet/Interop/PactHandle.cs
tests/PactNet.Tests/data/v2-consumer-integration.json
tests/PactNet.Tests/data/v3-consumer-integration.json
tests/PactNet.Tests/data/v3-message-consumer-integration.json
tests/PactNet.Tests/data/v3-server-integration.json

This is in preparation for replacing the existing verifier approach with a number of command-line style arguments with a proper handles approach, with the aim to introduce verifier logging.

chore: Upgrade to FFI 0.1.6

---

samples/EventApi/Consumer.Tests/EventsApiConsumerTests.cs
samples/EventImporter/Consumer.Tests/EventImporterTests.cs
samples/ReadMe/Consumer.Tests/SomethingApiConsumerTests.cs
src/PactNet.Abstractions/Constants.cs
src/PactNet.Abstractions/PactConfig.cs
src/PactNet/Interop/NativeInterop.cs
src/PactNet/PactExtensions.cs
tests/PactNet.Abstractions.Tests/PactConfigTests.cs

Remove the hard-coded log level and allow it to be specified during mock server setup

feat!: Configurable log level during consumer tests

---

tests/PactNet.Abstractions.Tests/Matchers/DecimalMatcherTests.cs
tests/PactNet.Abstractions.Tests/Matchers/NumericMatcherTests.cs

Fixes https://github.com/pact-foundation/pact-net/issues/354

fix: Make string comparison of JSON object representation culture invariant

---

.github/workflows/ci.yml
samples/EventApi/Consumer.Tests/Consumer.Tests.csproj
samples/EventApi/Consumer/Consumer.csproj
samples/EventApi/Provider.Tests/Provider.Tests.csproj
samples/EventApi/Provider/Provider.csproj
samples/EventImporter/Consumer.Tests/Consumer.Tests.csproj
samples/EventImporter/Consumer/Consumer.csproj
samples/EventImporter/Provider.Tests/Provider.Tests.csproj
samples/EventImporter/Provider/Provider.csproj
samples/ReadMe/Consumer.Tests/Readme.Consumer.Tests.csproj
samples/ReadMe/Consumer/Readme.Consumer.csproj
samples/ReadMe/Provider.Tests/Readme.Provider.Tests.csproj
samples/ReadMe/Provider/Readme.Provider.csproj
src/PactNet.Abstractions/PactNet.Abstractions.csproj
src/PactNet/PactNet.csproj
tests/PactNet.Abstractions.Tests/PactNet.Abstractions.Tests.csproj
tests/PactNet.Tests/PactNet.Tests.csproj

.Net Framework 4.6.1 and above support .Net Standard 2.0 so there's no real need to ship explicit .Net Framework support. We still run the tests on .Net Framework just to be sure that we've tested compatibility though.
This has the added bonus that the release CI can run on Ubuntu instead of Windows which means it's much much faster.

chore!: Upgrade to .net 6 and drop explicit .Net Framework support

---

src/PactNet.Abstractions/IRequestBuilder.cs
src/PactNet.Abstractions/IResponseBuilder.cs
src/PactNet/RequestBuilder.cs
src/PactNet/ResponseBuilder.cs
tests/PactNet.Tests/RequestBuilderTests.cs
tests/PactNet.Tests/ResponseBuilderTests.cs

Quite a simple change to just pass through some text as-is to use as the request or response body. The existing JSON methods can just run the serialiser and then pass the string result to the plain text version, so this is totally backwards compatible.
It would've been nice to use `Span<char>` instead of string, but since we're on `netstandard2.0` then that's not available.

feat: Support non-JSON request and response bodies (#391)

---

src/PactNet.Abstractions/Verifier/IPactBrokerOptions.cs
src/PactNet.Abstractions/Verifier/IPactUriOptions.cs
src/PactNet/Verifier/PactBrokerOptions.cs
src/PactNet/Verifier/PactUriOptions.cs
tests/PactNet.Tests/Verifier/PactBrokerOptionsTests.cs
tests/PactNet.Tests/Verifier/PactUriOptionsTests.cs

See the linked issue #392 for additional information
Draft currently as it's unclear where the broker URI is going to come from. Perhaps this is built into the FFI, but that doesn't seem safe to me.

feat: Allow publishing verification results for URI sources (#392)

---

build/download-native-libs.sh
samples/EventApi/Consumer.Tests/pacts/Event API Consumer-Event API.json
samples/Messaging/Consumer.Tests/pacts/Stock Event Consumer-Stock Event Producer.json
samples/ReadMe/pacts/Something API Consumer-Something API.json
tests/PactNet.Tests/data/v2-consumer-integration.json
tests/PactNet.Tests/data/v3-consumer-integration.json
tests/PactNet.Tests/data/v3-message-consumer-integration.json
tests/PactNet.Tests/data/v3-message-integration.json
tests/PactNet.Tests/data/v3-server-integration.json

This version of ffi on Linux only needs glibc 2.24 to run, which should make us more compatible across a larger set of Linux distributions.
Fixes: #402

chore: Upgrade FFI to 0.3.8

---

build/download-native-libs.sh
samples/EventApi/Consumer.Tests/pacts/Event API Consumer-Event API.json
samples/Messaging/Consumer.Tests/pacts/Stock Event Consumer-Stock Event Producer.json
samples/ReadMe/pacts/Something API Consumer-Something API.json
tests/PactNet.Tests/data/v2-consumer-integration.json
tests/PactNet.Tests/data/v3-consumer-integration.json
tests/PactNet.Tests/data/v3-message-consumer-integration.json
tests/PactNet.Tests/data/v3-message-integration.json
tests/PactNet.Tests/data/v3-server-integration.json

Upgraded FFI Version to 0.3.11. All tests passing locally. This version of FFI includes a fix for #417

chore: Upgrade FFI to version 0.3.11

---

build/download-native-libs.sh
src/PactNet/PactNet.csproj

Added arm64 ffi lib for M1 Mac's
See #347 for history

feat(arm64): add arm64 osx libs

---

build/download-native-libs.sh
samples/EventApi/Consumer.Tests/pacts/Event API Consumer-Event API.json
samples/Messaging/Consumer.Tests/pacts/Stock Event Consumer-Stock Event Producer.json
samples/ReadMe/pacts/Something API Consumer-Something API.json
tests/PactNet.Tests/data/v2-consumer-integration.json
tests/PactNet.Tests/data/v3-consumer-integration.json
tests/PactNet.Tests/data/v3-message-consumer-integration.json
tests/PactNet.Tests/data/v3-message-integration.json
tests/PactNet.Tests/data/v3-server-integration.json

This version includes a fix for https://github.com/pact-foundation/pact-reference/issues/231

chore: Upgrade FFI to version 0.4.0

---

CONTRIBUTING.md
README.md
build/download-native-libs.sh
src/PactNet/PactNet.csproj

Adds `libpact_ffi-linux-aarch64.so.gz` to support `linux-arm64` .NET target
Note: Unable to test via GitHub Actions until later in the year. [Source](https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/), although this has been validated both locally, and in CI systems (cirrus-ci)
Quote
> We expect to begin offering Arm runners for open source projects by the end of the year
This is advantageous for Docker users utilising Apple Silicon Mac's, as they are unable to leverage qemu for x64 binaries, as this is unsupported in .NET
Split out from #502 to only cover linux-aarch64(libc) case
It would be really nice if this managed to make the cut for the pact-net v5 release 🙏🏾

feat: support linux-arm64 runtime (libc)

---

README.md

Should 4.x be marked as deprecated, or is that still supported for a certain period of time, to allow for migration to 4.x and potentially allow for changes/fixes to be released to the 4.x line?

chore(docs): mark pact-net 5.x as stable

---

.github/workflows/ci.yml

Triggering on all 'push' and 'pull_request' events will result in duplicated CI runs in PRs (due to both conditions being met).
Instead, trigger only on pushes to `master`, or updates to PRs targetting `master`.

chore(ci): prevent duplicate ci triggers

---

.github/workflows/ci.yml

arm64 linux runners now available in GHA
see tracking issue - https://github.com/pact-foundation/roadmap/issues/19#issuecomment-2603270897
This PR adds coverage for linux arm64 (glibc) platforms in our CI

ci: add ubuntu-24.04-arm runner
